//! Static shortcut definitions compiled into core.

use crate::config::modules::TERMINAL_MODULE_NAME;

use super::model::{
    ShortcutActionStatic, ShortcutDefinition, ShortcutScopeStatic,
    ShortcutTriggerStatic, ShortcutTriggerStaticChord, ShortcutVisibility,
};

pub static SHORTCUT_DEFINITIONS: &[ShortcutDefinition] = &[
    ShortcutDefinition {
        id: "arcadia:dismiss-overlays",
        label: "Dismiss menus and modal overlays",
        owner: "arcadia",
        required_registry_module: None,
        scope: ShortcutScopeStatic::ArcadiaWide,
        visibility: ShortcutVisibility::Both,
        priority: 100,
        consumes: true,
        bypass_text_focus: true,
        system_wide: false,
        triggers: &[ShortcutTriggerStatic::Chord {
            key: "escape",
            control: false,
            alt: false,
            shift: false,
            platform: false,
            function: false,
        }],
        actions: &[ShortcutActionStatic::UiControl {
            control_id: "arcadia.dismiss_overlays",
        }],
    },
    ShortcutDefinition {
        id: "terminal:toggle-shell-mode",
        label: "Toggle shell execution mode (generic vs internal)",
        owner: "terminal",
        required_registry_module: Some(TERMINAL_MODULE_NAME),
        scope: ShortcutScopeStatic::Pages(&["utility.shell"]),
        visibility: ShortcutVisibility::Both,
        priority: 90,
        consumes: true,
        bypass_text_focus: false,
        system_wide: false,
        triggers: &[ShortcutTriggerStatic::Chord {
            key: "tab",
            control: false,
            alt: false,
            shift: true,
            platform: false,
            function: false,
        }],
        actions: &[ShortcutActionStatic::UiControl {
            control_id: "terminal.toggle_shell_mode",
        }],
    },
    ShortcutDefinition {
        id: "arcadia:os-global-modules",
        label: "OS-global — Modules (requires consent in Shortcuts settings)",
        owner: "arcadia",
        required_registry_module: None,
        scope: ShortcutScopeStatic::ArcadiaWide,
        visibility: ShortcutVisibility::GlobalPrefsOnly,
        priority: 8,
        consumes: false,
        bypass_text_focus: false,
        system_wide: true,
        triggers: &[ShortcutTriggerStatic::Chord {
            key: "m",
            control: true,
            alt: true,
            shift: true,
            platform: true,
            function: false,
        }],
        actions: &[ShortcutActionStatic::Navigate {
            page_id: "global.modules",
        }],
    },
    ShortcutDefinition {
        id: "demo:sequence-modules",
        label: "Sample chord sequence — Modules",
        owner: "arcadia",
        required_registry_module: None,
        scope: ShortcutScopeStatic::ArcadiaWide,
        visibility: ShortcutVisibility::GlobalPrefsOnly,
        priority: 5,
        consumes: true,
        bypass_text_focus: false,
        system_wide: false,
        triggers: &[ShortcutTriggerStatic::Sequence(&[
            ShortcutTriggerStaticChord {
                key: "comma",
                control: false,
                alt: false,
                shift: false,
                platform: true,
                function: false,
            },
            ShortcutTriggerStaticChord {
                key: "m",
                control: false,
                alt: false,
                shift: false,
                platform: true,
                function: false,
            },
        ])],
        actions: &[ShortcutActionStatic::Navigate {
            page_id: "global.modules",
        }],
    },
    ShortcutDefinition {
        id: "arcadia:command-bar",
        label: "Open command bar",
        owner: "arcadia",
        required_registry_module: None,
        scope: ShortcutScopeStatic::ArcadiaWide,
        visibility: ShortcutVisibility::Both,
        priority: 95,
        consumes: true,
        bypass_text_focus: false,
        system_wide: false,
        triggers: &[ShortcutTriggerStatic::Chord {
            key: "~",
            control: false,
            alt: false,
            shift: false,
            platform: false,
            function: false,
        }],
        actions: &[ShortcutActionStatic::UiControl {
            control_id: "arcadia.toggle_command_bar",
        }],
    },
];
